### ISSUE TITLE
Trouble building OortCommandLine

### ISSUE THREAD

**Issue by ShahimEssaid** [ShahimEssaid/owltools#103]
_From [jonathan...@gmail.com](https://code.google.com/u/113544480981201270938/) on September 26, 2014 08:30:04_

\<b>What steps will reproduce the problem?</b>
1. svn checkout \<a href="http://owltools.googlecode.com/svn/trunk/" rel="nofollow">http://owltools.googlecode.com/svn/trunk/</a> owltools-read-only&#13;
2. cd ./owltools-read-only/OWLTools-Parent&#13;
3. mvn clean package&#13;
&#13;
The expected output is a successful build of Oort Command Line Tools. Instead, errors are reported and the result is not a functioning build. An excerpt of maven's output that includes error messages is included below.&#13;
&#13;
The error occurs with a fresh copy of \<a href="http://owltools.googlecode.com/svn/trunk/" rel="nofollow">http://owltools.googlecode.com/svn/trunk/</a> obtained on Friday, September 26 2014 by following step (1) above. The versions of Maven, Java, and Linux used are as follows:&#13;
&#13;
$ mvn -V&#13;
Apache Maven 3.0.4&#13;
Maven home: /usr/share/maven&#13;
Java version: 1.7.0_65, vendor: Oracle Corporation&#13;
Java home: /usr/lib/jvm/java-7-openjdk-i386/jre&#13;
Default locale: en_US, platform encoding: UTF-8&#13;
OS name: "linux", version: "3.2.0-68-generic", arch: "i386", family: "unix"&#13;
&#13;
&#13;
I experienced a similar issue last week trying to build on Mac OS 10.9.5&#13;
&#13;
&#13;
---Maven excerpt-----&#13;
&#13;
\### Annotations:&#13;
&#13;
 * [comment](<a href="http://www.w3.org/2000/01/rdf-schema#comment" rel="nofollow">http://www.w3.org/2000/01/rdf-schema#comment</a>) : &#13;
          foo&#13;
        &#13;
 * [creator](<a href="http://purl.org/dc/elements/1.1/creator" rel="nofollow">http://purl.org/dc/elements/1.1/creator</a>) : Gene Ontology Consortium&#13;
 * [homepage](<a href="http://xmlns.com/foaf/0.1/homepage" rel="nofollow">http://xmlns.com/foaf/0.1/homepage</a>) : [<a href="http://wiki.geneontology.org/index.php/Ontology_extensions](http://wiki.geneontology.org/index.php/Ontology_extensions)" rel="nofollow">http://wiki.geneontology.org/index.php/Ontology_extensions](http://wiki.geneontology.org/index.php/Ontology_extensions)</a>&#13;
 * [publisher](<a href="http://purl.org/dc/elements/1.1/publisher" rel="nofollow">http://purl.org/dc/elements/1.1/publisher</a>) : Gene Ontology Consortium&#13;
&#13;
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec&#13;
&#13;
Results :&#13;
&#13;
Tests in error: &#13;
  testConvertXPs(owltools.CycleTest): Unexpected end of file from server&#13;
&#13;
Tests run: 144, Failures: 0, Errors: 1, Skipped: 3&#13;
&#13;
[INFO] ------------------------------------------------------------------------&#13;
[INFO] Reactor Summary:&#13;
[INFO] &#13;
[INFO] OWLTools-Parent ................................... SUCCESS [43.531s]&#13;
[INFO] OWLTools-Core ..................................... FAILURE [13:42.922s]&#13;
[INFO] Lego .............................................. SKIPPED&#13;
[INFO] OWLTools-Annotation ............................... SKIPPED&#13;
[INFO] OWLTools-Oort ..................................... SKIPPED&#13;
[INFO] OWLTools-Sim ...................................... SKIPPED&#13;
[INFO] OWLTools-Web ...................................... SKIPPED&#13;
[INFO] OWLTools-Solr ..................................... SKIPPED&#13;
[INFO] OWLTools-Runner ................................... SKIPPED&#13;
[INFO] OWLTools-NCBI ..................................... SKIPPED&#13;
[INFO] MolecularModelServer .............................. SKIPPED&#13;
[INFO] Golr-Client ....................................... SKIPPED&#13;
[INFO] ------------------------------------------------------------------------&#13;
[INFO] BUILD FAILURE&#13;
[INFO] ------------------------------------------------------------------------&#13;
[INFO] Total time: 14:26.784s&#13;
[INFO] Finished at: Fri Sep 26 11:08:26 EDT 2014&#13;
[INFO] Final Memory: 20M/69M&#13;
[INFO] ------------------------------------------------------------------------&#13;
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.2:test (default-test) on project OWLTools-Core: There are test failures.&#13;
[ERROR] &#13;
[ERROR] Please refer to /home/jonathanbona/Desktop/owltools-read-only/OWLTools-Core/target/surefire-reports for the individual test results.&#13;
[ERROR] -&gt; [Help 1]&#13;
[ERROR] &#13;
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.&#13;
[ERROR] Re-run Maven using the -X switch to enable full debug logging.&#13;
[ERROR] &#13;
[ERROR] For more information about the errors and possible solutions, please read the following articles:&#13;
[ERROR] [Help 1] \<a href="http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException" rel="nofollow">http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException</a>&#13;
[ERROR] &#13;
[ERROR] After correcting the problems, you can resume the build with the command&#13;
[ERROR]   mvn &lt;goals&gt; -rf :OWLTools-Core&#13;

_Original issue: http://code.google.com/p/owltools/issues/detail?id=103_

**Comment by ShahimEssaid** [comment]
_From [HDie...@lbl.gov](https://code.google.com/u/115902121950964170841/) on September 26, 2014 10:05:11_

Hello,
thank you for reporting the issue. The problem with this particular test is that it tries to load an ontology via an HTTP request. This may fail for numerous reasons.

To prevent further false positive, I have added an ignore tag to this test.

In general, we have a continuous integration test running here: http://build.berkeleybop.org/job/owltools/ As long as this jobs runs though okay, we assume the owltools build is okay.

**Status:** Fixed

**Comment by ShahimEssaid** [comment]
_From [jonathan...@gmail.com](https://code.google.com/u/113544480981201270938/) on September 26, 2014 12:31:42_

Thanks!
